// <auto-generated />
namespace MySensei.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test71 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test71));
        
        string IMigrationMetadata.Id
        {
            get { return "201512021630071_test71"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
